/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "platform_types.h"

#define RCC_BASE 0x40021000
#define PORTA_BASE 0x40010800

#define RCC_ENR		*(vuint32_t *)(RCC_BASE + 0X18)
#define GPIOA_CRH	*(vuint32_t *)(PORTA_BASE + 0x04)
#define GPIOA_ODR	*(vuint32_t *)(PORTA_BASE + 0x0c)


typedef union{
	vuint32_t ALL_P;
	struct{
		vuint32_t unwanted:13;
		vuint32_t p13:1;
	}Spins;
}ODR_R_t;
volatile ODR_R_t* ODR_R = (volatile ODR_R_t*) (PORTA_BASE + 0x0c);
int main(void)
{
	RCC_ENR |= 1<<2;
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;

	while(1)
	{
		ODR_R -> Spins.p13 = 1;
		for (int i = 0; i < 100000; i++);
		ODR_R -> Spins.p13 = 0;
		for (int i = 0; i < 100000; i++);
	}
}
